version: '3.0'

x-service-common:
  &service-common
  image: openai-relay:0.0.1
  command: --workers=4
  ports:
    - "8000:8000"
  environment:
    SELECT_URL: mysql+aiomysql://root:123456@localhost:3306/openai
    REDIS_URL: redis://:123456@localhost:6379/1
    KAFKA_URI: localhost:9092
    KAFKA_OPENAI_TOPIC: openai-relay-v1
    LOG_PATH: logs
  volumes:
    - ./logs:/app/logs
  deploy:
    resources:
      limits:
        memory: 1G
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: '10'
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:8000/ping" ]
    interval: 30s
    timeout: 5s
    retries: 3
  restart: on-failure:3

services:
  ant-openai-relay-1:
    <<: *service-common
    container_name: ant-openai-relay-1
    ports:
      - "18001:8000"

  ant-openai-relay-2:
    <<: *service-common
    container_name: ant-openai-relay-2
    ports:
      - "18002:8000"

  ant-openai-relay-3:
    <<: *service-common
    container_name: ant-openai-relay-3
    ports:
      - "18003:8000"

  down-haproxy:
    image: haproxy:2.6.6-alpine3.16
    container_name: openai-haproxy
    hostname: openai-haproxy
    ports:
      - 13390:13390
      - 38801:38801
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    deploy:
      resources:
        limits:
          memory: 1G
